baseURL = "https://isalman.dev"
languageCode = "zh-cn"
title = "Salman's blog"
theme = "github-style"
googleAnalytics = "G-005SCZ0FF4"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Salman Qureshi"
  description = "Your friendly neighbourhood printer fixer 🫠"
  github = "hotheadhacker"
  twitter = "salmanually"
  instagram = "salmanually"
  email = "contact@isalman.dev"
  url = "https://isalman.dev"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/avatar.png"
  location = "Kashmir"
  enableGitalk = true

  [params.gitalk]
    clientID = "4faed7d62c722f3b70f8" 
    clientSecret = "ead79bc481425394dd8e1f0fdc3ed40aa639751a" 
    repo = "blog-comments"
    owner = "hotheadhacker"
    admin = "hotheadhacker"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://github.com/hotheadhacker"
  [[params.links]]
    title = "Link2"
    href = "https://isalman.dev"
    icon = "https://avatars.githubusercontent.com/u/18418340?s=400&u=b5fe00151650174cfff9ff47dd3e0699c33f1774&v=4"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
